#!/bin/bash
#SBATCH --job-name=run_7b
#SBATCH --output=results/run_7b_%j.out
#SBATCH --error=results/run_7b_%j.err
#SBATCH --partition=dev_gpu_4_a100
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --time=30:00
#SBATCH --nodes=1
#SBATCH --mail-type=NONE

cd $SLURM_SUBMIT_DIR

source ~/.bashrc
module load devel/cuda
conda activate eval

echo "run_7b"
echo "GPU:1"
echo
echo "NVDIA-SMI OUTPUT"
nvidia-smi

cd ~/llms/mthesis/code

poetry run main test --stats stats_7b.yml --settings settings/settings_7b.yml
